# Generated by Django 3.2.8 on 2021-10-31 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('Gpname', models.CharField(max_length=25)),
                ('GpID', models.IntegerField(primary_key=True, serialize=False)),
                ('GpDescription', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('uid', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='GroupImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ImageID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('Image', models.ImageField(default='DefaultImages/default-image-620x600.jpg', upload_to='images/')),
                ('GpID', models.ForeignKey(default=8888, on_delete=django.db.models.deletion.CASCADE, to='API.group')),
            ],
        ),
        migrations.AddField(
            model_name='group',
            name='teamMember',
            field=models.ManyToManyField(to='API.User'),
        ),
    ]
