# Generated by Django 3.2.8 on 2021-10-28 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
