# Generated by Django 3.2.8 on 2021-11-21 03:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='BookSome',
        ),
    ]
