# Generated by Django 3.2.9 on 2021-11-19 21:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimages',
            name='save_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
