# Generated by Django 3.2.8 on 2021-11-01 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='isDefault',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='images/Avatars/default_avatar.jpeg', upload_to='images/Avatars'),
        ),
        migrations.AlterField(
            model_name='group',
            name='GpID',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='GroupCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CodeID', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=50)),
                ('Code', models.FileField(default=None, upload_to='Code/')),
                ('GpID', models.ForeignKey(default=8888, on_delete=django.db.models.deletion.CASCADE, to='API.group')),
                ('ImageID', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='API.groupimages')),
            ],
        ),
    ]
