# Generated by Django 3.2.9 on 2021-11-30 08:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_auto_20211101_0627'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='leader_uid',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='groupimages',
            name='Code',
            field=models.TextField(default='Need_To_Discard'),
        ),
        migrations.AddField(
            model_name='groupimages',
            name='Image_after',
            field=models.ImageField(null=True, upload_to='images/OCR/'),
        ),
        migrations.AddField(
            model_name='groupimages',
            name='Image_after_url',
            field=models.URLField(null=True),
        ),
        migrations.AddField(
            model_name='groupimages',
            name='save_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='groupimages',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default=None, upload_to='Avatars'),
        ),
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='GroupCode',
        ),
    ]
