# Generated by Django 3.2.9 on 2021-11-28 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_groupimages_save_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimages',
            name='Image_after_url',
            field=models.URLField(null=True),
        ),
    ]
