# Generated by Django 3.2.8 on 2021-11-21 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0002_rename_book_booksome'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimages',
            name='Code',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='groupimages',
            name='GpID',
            field=models.ForeignKey(default=8888, on_delete=django.db.models.deletion.CASCADE, to='API.group'),
        ),
        migrations.AlterField(
            model_name='groupimages',
            name='Image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
        migrations.DeleteModel(
            name='BookSome',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
    ]
