# Generated by Django 3.2.7 on 2021-10-14 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_groupimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupimages',
            name='GpID',
        ),
        migrations.AddField(
            model_name='groupimages',
            name='GpID',
            field=models.ForeignKey(default=8888, on_delete=django.db.models.deletion.CASCADE, to='API.group'),
        ),
        migrations.AlterField(
            model_name='groupimages',
            name='Image',
            field=models.ImageField(default='DefaultImages/default-image-620x600.jpg', upload_to='images/'),
        ),
    ]
