# Generated by Django 3.2.8 on 2021-11-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_auto_20211121_0702'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupimages',
            name='Image_after',
            field=models.ImageField(null=True, upload_to='images/OCR/'),
        ),
    ]
