# Generated by Django 3.2.7 on 2021-10-14 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20211014_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='PW',
            field=models.IntegerField(default=9999),
        ),
    ]
